/*
 * Dante Web Services
 *       # Introduction   Dante is an API Web Service used for iteract with earthquake data stored in database (**quakedb**); the **quakedb** database schema is used at INGV.   Use other schema would require cration of specific `Model` and `Controller` but this is the potential of web services.      Dante provides a set of routes to store message **event**, **origin**, **magnitude**, **arrival**, **...**.      # Input   As input, Dante acept:   - A `json` message (view '**store**' spec below)    - An Eartworm `json` message (view '**earthworm api**' spec below) produced by **ew2openapi** module      # Output   As output, Dante has a RESTful api foreach database table and implement three specific routes:    - `events-group`: returns the preferred origin and the preferred magnitude from all clusterd events.    - `events`: returns the preferred origin and the preferred magnitude from the same instance.    - `event`: returns the full event (event, origins, magnitudes, arrivals, amplitude, etc...) from an **eventid** or **originid**_/_**originid**.        
 *
 * The version of the OpenAPI document: 3.12.0-dev
 * Contact: valentino.lauciani@ingv.it
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.ingv.dante.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ObjectMomenttensorTdmtStationsInner
 */
public class ObjectMomenttensorTdmtStationsInnerTest {
    private final ObjectMomenttensorTdmtStationsInner model = new ObjectMomenttensorTdmtStationsInner();

    /**
     * Model tests for ObjectMomenttensorTdmtStationsInner
     */
    @Test
    public void testObjectMomenttensorTdmtStationsInner() {
        // TODO: test ObjectMomenttensorTdmtStationsInner
    }

    /**
     * Test the property 'sta'
     */
    @Test
    public void staTest() {
        // TODO: test sta
    }

    /**
     * Test the property 'r'
     */
    @Test
    public void rTest() {
        // TODO: test r
    }

    /**
     * Test the property 'azi'
     */
    @Test
    public void aziTest() {
        // TODO: test azi
    }

    /**
     * Test the property 'w'
     */
    @Test
    public void wTest() {
        // TODO: test w
    }

    /**
     * Test the property 'vr'
     */
    @Test
    public void vrTest() {
        // TODO: test vr
    }

    /**
     * Test the property 'zcor'
     */
    @Test
    public void zcorTest() {
        // TODO: test zcor
    }

    /**
     * Test the property 'modified'
     */
    @Test
    public void modifiedTest() {
        // TODO: test modified
    }

    /**
     * Test the property 'inserted'
     */
    @Test
    public void insertedTest() {
        // TODO: test inserted
    }

}
