/*
 * Dante Web Services
 * # Introduction  Dante is a RESTful API service designed to interact with seismic data stored in the **quakedb** database schema used at INGV. Dante can be extended to other database schemas by creating custom `Model` and `Controller` implementations.  Dante provides a set of routes to store message: **event**, **origin**, **magnitude**, **arrival**, **...**.  ## Input  Dante accepts: - A `json` message (view '**store**' spec below). - An Eartworm `json` message (view '**earthworm api**' spec below) produced by **ew2openapi** module.  ## Output  Dante exposes RESTful routes for each database table and implements three specialized endpoints: - `/events-group`: returns the preferred origin and magnitude for all clustered events. - `/events`: returns the preferred origin and magnitude for a single event instance. - `/event`: returns the full event details (event, origins, magnitudes, arrivals, amplitudes, etc.) based on an **eventid** or **originid**. 
 *
 * The version of the OpenAPI document: 3.48.0-dev
 * Contact: valentino.lauciani@ingv.it
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.ingv.dante.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.ingv.dante.model.ObjectLocalspace;
import org.ingv.dante.model.ObjectProvenance;
import org.ingv.dante.model.ObjectStrongmotionAlternative;
import org.ingv.dante.model.ObjectStrongmotionRsaInner;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ObjectStrongmotion
 */
public class ObjectStrongmotionTest {
    private final ObjectStrongmotion model = new ObjectStrongmotion();

    /**
     * Model tests for ObjectStrongmotion
     */
    @Test
    public void testObjectStrongmotion() {
        // TODO: test ObjectStrongmotion
    }

    /**
     * Test the property 'net'
     */
    @Test
    public void netTest() {
        // TODO: test net
    }

    /**
     * Test the property 'sta'
     */
    @Test
    public void staTest() {
        // TODO: test sta
    }

    /**
     * Test the property 'cha'
     */
    @Test
    public void chaTest() {
        // TODO: test cha
    }

    /**
     * Test the property 'loc'
     */
    @Test
    public void locTest() {
        // TODO: test loc
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'modified'
     */
    @Test
    public void modifiedTest() {
        // TODO: test modified
    }

    /**
     * Test the property 'inserted'
     */
    @Test
    public void insertedTest() {
        // TODO: test inserted
    }

    /**
     * Test the property 'idLocalspace'
     */
    @Test
    public void idLocalspaceTest() {
        // TODO: test idLocalspace
    }

    /**
     * Test the property 'tDt'
     */
    @Test
    public void tDtTest() {
        // TODO: test tDt
    }

    /**
     * Test the property 'pga'
     */
    @Test
    public void pgaTest() {
        // TODO: test pga
    }

    /**
     * Test the property 'tpgaDt'
     */
    @Test
    public void tpgaDtTest() {
        // TODO: test tpgaDt
    }

    /**
     * Test the property 'pgv'
     */
    @Test
    public void pgvTest() {
        // TODO: test pgv
    }

    /**
     * Test the property 'tpgvDt'
     */
    @Test
    public void tpgvDtTest() {
        // TODO: test tpgvDt
    }

    /**
     * Test the property 'pgd'
     */
    @Test
    public void pgdTest() {
        // TODO: test pgd
    }

    /**
     * Test the property 'tpgdDt'
     */
    @Test
    public void tpgdDtTest() {
        // TODO: test tpgdDt
    }

    /**
     * Test the property 'rsa030'
     */
    @Test
    public void rsa030Test() {
        // TODO: test rsa030
    }

    /**
     * Test the property 'rsa100'
     */
    @Test
    public void rsa100Test() {
        // TODO: test rsa100
    }

    /**
     * Test the property 'rsa300'
     */
    @Test
    public void rsa300Test() {
        // TODO: test rsa300
    }

    /**
     * Test the property 'localspace'
     */
    @Test
    public void localspaceTest() {
        // TODO: test localspace
    }

    /**
     * Test the property 'provenance'
     */
    @Test
    public void provenanceTest() {
        // TODO: test provenance
    }

    /**
     * Test the property 'alternative'
     */
    @Test
    public void alternativeTest() {
        // TODO: test alternative
    }

    /**
     * Test the property 'rsa'
     */
    @Test
    public void rsaTest() {
        // TODO: test rsa
    }

}
