/*
 * Dante Web Services
 *       # Introduction   Dante is an API Web Service used for iteract with earthquake data stored in database (**quakedb**); the **quakedb** database schema is used at INGV.   Use other schema would require cration of specific `Model` and `Controller` but this is the potential of web services.      Dante provides a set of routes to store message **event**, **origin**, **magnitude**, **arrival**, **...**.      # Input   As input, Dante acept:   - A `json` message (view '**store**' spec below)    - An Eartworm `json` message (view '**earthworm api**' spec below) produced by **ew2openapi** module      # Output   As output, Dante has a RESTful api foreach database table and implement three specific routes:    - `events-group`: returns the preferred origin and the preferred magnitude from all clusterd events.    - `events`: returns the preferred origin and the preferred magnitude from the same instance.    - `event`: returns the full event (event, origins, magnitudes, arrivals, amplitude, etc...) from an **eventid** or **originid**_/_**originid**.        
 *
 * The version of the OpenAPI document: 3.47.0-dev
 * Contact: valentino.lauciani@ingv.it
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.ingv.dante.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.ingv.dante.model.ObjectLocalspaceForVw;
import org.ingv.dante.model.ObjectMagnitudeForMagnitudesOriginsEventsAndEventsGroup;
import org.ingv.dante.model.ObjectOriginForMagnitudesOriginsEventsAndEventsGroup;
import org.ingv.dante.model.ObjectProvenaceForMagnitudesOriginsEventsAndEventsGroup;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ObjectMagnitudesOriginsEventsAndEventsGroup
 */
public class ObjectMagnitudesOriginsEventsAndEventsGroupTest {
    private final ObjectMagnitudesOriginsEventsAndEventsGroup model = new ObjectMagnitudesOriginsEventsAndEventsGroup();

    /**
     * Model tests for ObjectMagnitudesOriginsEventsAndEventsGroup
     */
    @Test
    public void testObjectMagnitudesOriginsEventsAndEventsGroup() {
        // TODO: test ObjectMagnitudesOriginsEventsAndEventsGroup
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'idLocalspace'
     */
    @Test
    public void idLocalspaceTest() {
        // TODO: test idLocalspace
    }

    /**
     * Test the property 'eventGroupId'
     */
    @Test
    public void eventGroupIdTest() {
        // TODO: test eventGroupId
    }

    /**
     * Test the property 'preferredOriginId'
     */
    @Test
    public void preferredOriginIdTest() {
        // TODO: test preferredOriginId
    }

    /**
     * Test the property 'preferredMagnitudeId'
     */
    @Test
    public void preferredMagnitudeIdTest() {
        // TODO: test preferredMagnitudeId
    }

    /**
     * Test the property 'preferredFocalmechanismId'
     */
    @Test
    public void preferredFocalmechanismIdTest() {
        // TODO: test preferredFocalmechanismId
    }

    /**
     * Test the property 'flags'
     */
    @Test
    public void flagsTest() {
        // TODO: test flags
    }

    /**
     * Test the property 'typeGroup'
     */
    @Test
    public void typeGroupTest() {
        // TODO: test typeGroup
    }

    /**
     * Test the property 'typeEvent'
     */
    @Test
    public void typeEventTest() {
        // TODO: test typeEvent
    }

    /**
     * Test the property 'origindirectlinktoevent'
     */
    @Test
    public void origindirectlinktoeventTest() {
        // TODO: test origindirectlinktoevent
    }

    /**
     * Test the property 'magnitudedirectlinktoorigin'
     */
    @Test
    public void magnitudedirectlinktooriginTest() {
        // TODO: test magnitudedirectlinktoorigin
    }

    /**
     * Test the property 'magnitudedirectlinktoevent'
     */
    @Test
    public void magnitudedirectlinktoeventTest() {
        // TODO: test magnitudedirectlinktoevent
    }

    /**
     * Test the property 'modified'
     */
    @Test
    public void modifiedTest() {
        // TODO: test modified
    }

    /**
     * Test the property 'inserted'
     */
    @Test
    public void insertedTest() {
        // TODO: test inserted
    }

    /**
     * Test the property 'localspace'
     */
    @Test
    public void localspaceTest() {
        // TODO: test localspace
    }

    /**
     * Test the property 'provenance'
     */
    @Test
    public void provenanceTest() {
        // TODO: test provenance
    }

    /**
     * Test the property 'origin'
     */
    @Test
    public void originTest() {
        // TODO: test origin
    }

    /**
     * Test the property 'magnitude'
     */
    @Test
    public void magnitudeTest() {
        // TODO: test magnitude
    }

}
