/*
 * Dante Web Services
 * # Introduction  Dante is a RESTful API service designed to interact with seismic data stored in the **quakedb** database schema used at INGV. Dante can be extended to other database schemas by creating custom `Model` and `Controller` implementations.  Dante provides a set of routes to store message: **event**, **origin**, **magnitude**, **arrival**, **...**.  ## Input  Dante accepts: - A `json` message (view '**store**' spec below). - An Eartworm `json` message (view '**earthworm api**' spec below) produced by **ew2openapi** module.  ## Output  Dante exposes RESTful routes for each database table and implements three specialized endpoints: - `/events-group`: returns the preferred origin and magnitude for all clustered events. - `/events`: returns the preferred origin and magnitude for a single event instance. - `/event`: returns the full event details (event, origins, magnitudes, arrivals, amplitudes, etc.) based on an **eventid** or **originid**. 
 *
 * The version of the OpenAPI document: 3.48.0-dev
 * Contact: valentino.lauciani@ingv.it
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.ingv.dante.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.ingv.dante.model.ObjectAmplitude;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ObjectStationmagnitude
 */
public class ObjectStationmagnitudeTest {
    private final ObjectStationmagnitude model = new ObjectStationmagnitude();

    /**
     * Model tests for ObjectStationmagnitude
     */
    @Test
    public void testObjectStationmagnitude() {
        // TODO: test ObjectStationmagnitude
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'epDistanceKm'
     */
    @Test
    public void epDistanceKmTest() {
        // TODO: test epDistanceKm
    }

    /**
     * Test the property 'origDistanceKm'
     */
    @Test
    public void origDistanceKmTest() {
        // TODO: test origDistanceKm
    }

    /**
     * Test the property 'azimut'
     */
    @Test
    public void azimutTest() {
        // TODO: test azimut
    }

    /**
     * Test the property 'mag'
     */
    @Test
    public void magTest() {
        // TODO: test mag
    }

    /**
     * Test the property 'errMag'
     */
    @Test
    public void errMagTest() {
        // TODO: test errMag
    }

    /**
     * Test the property 'weight'
     */
    @Test
    public void weightTest() {
        // TODO: test weight
    }

    /**
     * Test the property 'magCorrection'
     */
    @Test
    public void magCorrectionTest() {
        // TODO: test magCorrection
    }

    /**
     * Test the property 'isUsed'
     */
    @Test
    public void isUsedTest() {
        // TODO: test isUsed
    }

    /**
     * Test the property 'typeMagnitude'
     */
    @Test
    public void typeMagnitudeTest() {
        // TODO: test typeMagnitude
    }

    /**
     * Test the property 'modified'
     */
    @Test
    public void modifiedTest() {
        // TODO: test modified
    }

    /**
     * Test the property 'inserted'
     */
    @Test
    public void insertedTest() {
        // TODO: test inserted
    }

    /**
     * Test the property 'amplitude'
     */
    @Test
    public void amplitudeTest() {
        // TODO: test amplitude
    }

}
