/*
 * Dante Web Services
 *       # Introduction   Dante is an API Web Service used for iteract with earthquake data stored in database (**quakedb**); the **quakedb** database schema is used at INGV.   Use other schema would require cration of specific `Model` and `Controller` but this is the potential of web services.      Dante provides a set of routes to store message **event**, **origin**, **magnitude**, **arrival**, **...**.      # Input   As input, Dante acept:   - A `json` message (view '**store**' spec below)    - An Eartworm `json` message (view '**earthworm api**' spec below) produced by **ew2openapi** module      # Output   As output, Dante has a RESTful api foreach database table and implement three specific routes:    - `events-group`: returns the preferred origin and the preferred magnitude from all clusterd events.    - `events`: returns the preferred origin and the preferred magnitude from the same instance.    - `event`: returns the full event (event, origins, magnitudes, arrivals, amplitude, etc...) from an **eventid** or **originid**_/_**originid**.        
 *
 * The version of the OpenAPI document: 3.36.0
 * Contact: valentino.lauciani@ingv.it
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.ingv.dante.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.ingv.dante.model.ObjectAmplitudeTypeAmplitude;
import org.ingv.dante.model.ObjectLocalspace;
import org.ingv.dante.model.ObjectProvenance;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ObjectAmplitude
 */
public class ObjectAmplitudeTest {
    private final ObjectAmplitude model = new ObjectAmplitude();

    /**
     * Model tests for ObjectAmplitude
     */
    @Test
    public void testObjectAmplitude() {
        // TODO: test ObjectAmplitude
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'idLocalspace'
     */
    @Test
    public void idLocalspaceTest() {
        // TODO: test idLocalspace
    }

    /**
     * Test the property 'net'
     */
    @Test
    public void netTest() {
        // TODO: test net
    }

    /**
     * Test the property 'sta'
     */
    @Test
    public void staTest() {
        // TODO: test sta
    }

    /**
     * Test the property 'cha'
     */
    @Test
    public void chaTest() {
        // TODO: test cha
    }

    /**
     * Test the property 'loc'
     */
    @Test
    public void locTest() {
        // TODO: test loc
    }

    /**
     * Test the property 'time1'
     */
    @Test
    public void time1Test() {
        // TODO: test time1
    }

    /**
     * Test the property 'amp1'
     */
    @Test
    public void amp1Test() {
        // TODO: test amp1
    }

    /**
     * Test the property 'time2'
     */
    @Test
    public void time2Test() {
        // TODO: test time2
    }

    /**
     * Test the property 'amp2'
     */
    @Test
    public void amp2Test() {
        // TODO: test amp2
    }

    /**
     * Test the property 'pickId'
     */
    @Test
    public void pickIdTest() {
        // TODO: test pickId
    }

    /**
     * Test the property 'period'
     */
    @Test
    public void periodTest() {
        // TODO: test period
    }

    /**
     * Test the property 'revised'
     */
    @Test
    public void revisedTest() {
        // TODO: test revised
    }

    /**
     * Test the property 'typeAmplitude'
     */
    @Test
    public void typeAmplitudeTest() {
        // TODO: test typeAmplitude
    }

    /**
     * Test the property 'localspace'
     */
    @Test
    public void localspaceTest() {
        // TODO: test localspace
    }

    /**
     * Test the property 'provenance'
     */
    @Test
    public void provenanceTest() {
        // TODO: test provenance
    }

    /**
     * Test the property 'modified'
     */
    @Test
    public void modifiedTest() {
        // TODO: test modified
    }

    /**
     * Test the property 'inserted'
     */
    @Test
    public void insertedTest() {
        // TODO: test inserted
    }

    /**
     * Test the property 'timewindowReference'
     */
    @Test
    public void timewindowReferenceTest() {
        // TODO: test timewindowReference
    }

}
