/*
 * Dante Web Services
 *       # Introduction   Dante is an API Web Service used for iteract with earthquake data stored in database (**quakedb**); the **quakedb** database schema is used at INGV.   Use other schema would require cration of specific `Model` and `Controller` but this is the potential of web services.      Dante provides a set of routes to store message **event**, **origin**, **magnitude**, **arrival**, **...**.      # Input   As input, Dante acept:   - A `json` message (view '**store**' spec below)    - An Eartworm `json` message (view '**earthworm api**' spec below) produced by **ew2openapi** module      # Output   As output, Dante has a RESTful api foreach database table and implement three specific routes:    - `events-group`: returns the preferred origin and the preferred magnitude from all clusterd events.    - `events`: returns the preferred origin and the preferred magnitude from the same instance.    - `event`: returns the full event (event, origins, magnitudes, arrivals, amplitude, etc...) from an **eventid** or **originid**_/_**originid**.        
 *
 * The version of the OpenAPI document: 2.78.0-dev
 * Contact: valentino.lauciani@ingv.it
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.ingv.dante.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import org.ingv.dante.model.ObjectLocalspace;
import org.ingv.dante.model.ObjectPickEw;
import org.ingv.dante.model.ObjectProvenance;
import org.ingv.dante.model.PickEmersio;
import org.ingv.dante.model.PickFirstmotion;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ObjectArrival
 */
public class ObjectArrivalTest {
    private final ObjectArrival model = new ObjectArrival();

    /**
     * Model tests for ObjectArrival
     */
    @Test
    public void testObjectArrival() {
        // TODO: test ObjectArrival
    }

    /**
     * Test the property 'net'
     */
    @Test
    public void netTest() {
        // TODO: test net
    }

    /**
     * Test the property 'sta'
     */
    @Test
    public void staTest() {
        // TODO: test sta
    }

    /**
     * Test the property 'cha'
     */
    @Test
    public void chaTest() {
        // TODO: test cha
    }

    /**
     * Test the property 'loc'
     */
    @Test
    public void locTest() {
        // TODO: test loc
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'modified'
     */
    @Test
    public void modifiedTest() {
        // TODO: test modified
    }

    /**
     * Test the property 'inserted'
     */
    @Test
    public void insertedTest() {
        // TODO: test inserted
    }

    /**
     * Test the property 'idLocalspace'
     */
    @Test
    public void idLocalspaceTest() {
        // TODO: test idLocalspace
    }

    /**
     * Test the property 'iscCode'
     */
    @Test
    public void iscCodeTest() {
        // TODO: test iscCode
    }

    /**
     * Test the property 'qualityClass'
     */
    @Test
    public void qualityClassTest() {
        // TODO: test qualityClass
    }

    /**
     * Test the property 'lowerUncertainty'
     */
    @Test
    public void lowerUncertaintyTest() {
        // TODO: test lowerUncertainty
    }

    /**
     * Test the property 'upperUncertainty'
     */
    @Test
    public void upperUncertaintyTest() {
        // TODO: test upperUncertainty
    }

    /**
     * Test the property 'confidenceLevel'
     */
    @Test
    public void confidenceLevelTest() {
        // TODO: test confidenceLevel
    }

    /**
     * Test the property 'arrivalTime'
     */
    @Test
    public void arrivalTimeTest() {
        // TODO: test arrivalTime
    }

    /**
     * Test the property 'firstmotion'
     */
    @Test
    public void firstmotionTest() {
        // TODO: test firstmotion
    }

    /**
     * Test the property 'emersio'
     */
    @Test
    public void emersioTest() {
        // TODO: test emersio
    }

    /**
     * Test the property 'epDistanceKm'
     */
    @Test
    public void epDistanceKmTest() {
        // TODO: test epDistanceKm
    }

    /**
     * Test the property 'epDistanceDelta'
     */
    @Test
    public void epDistanceDeltaTest() {
        // TODO: test epDistanceDelta
    }

    /**
     * Test the property 'origDistance'
     */
    @Test
    public void origDistanceTest() {
        // TODO: test origDistance
    }

    /**
     * Test the property 'azimut'
     */
    @Test
    public void azimutTest() {
        // TODO: test azimut
    }

    /**
     * Test the property 'takeOff'
     */
    @Test
    public void takeOffTest() {
        // TODO: test takeOff
    }

    /**
     * Test the property 'polarityIsUsed'
     */
    @Test
    public void polarityIsUsedTest() {
        // TODO: test polarityIsUsed
    }

    /**
     * Test the property 'arrTimeIsUsed'
     */
    @Test
    public void arrTimeIsUsedTest() {
        // TODO: test arrTimeIsUsed
    }

    /**
     * Test the property 'residual'
     */
    @Test
    public void residualTest() {
        // TODO: test residual
    }

    /**
     * Test the property 'weight'
     */
    @Test
    public void weightTest() {
        // TODO: test weight
    }

    /**
     * Test the property 'localspace'
     */
    @Test
    public void localspaceTest() {
        // TODO: test localspace
    }

    /**
     * Test the property 'provenance'
     */
    @Test
    public void provenanceTest() {
        // TODO: test provenance
    }

    /**
     * Test the property 'pickEw'
     */
    @Test
    public void pickEwTest() {
        // TODO: test pickEw
    }

}
