/*
 * Dante Web Services
 * # Introduction  Dante is a RESTful API service designed to interact with seismic data stored in the **quakedb** database schema used at INGV. Dante can be extended to other database schemas by creating custom `Model` and `Controller` implementations.  Dante provides a set of routes to store message: **event**, **origin**, **magnitude**, **arrival**, **...**.  ## Input  Dante accepts: - A `json` message (view '**store**' spec below). - An Eartworm `json` message (view '**earthworm api**' spec below) produced by **ew2openapi** module.  ## Output  Dante exposes RESTful routes for each database table and implements three specialized endpoints: - `/events-group`: returns the preferred origin and magnitude for all clustered events. - `/events`: returns the preferred origin and magnitude for a single event instance. - `/event`: returns the full event details (event, origins, magnitudes, arrivals, amplitudes, etc.) based on an **eventid** or **originid**. 
 *
 * The version of the OpenAPI document: 3.48.0-dev
 * Contact: valentino.lauciani@ingv.it
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.ingv.dante.api;

import org.ingv.dante.ApiException;
import org.ingv.dante.model.AddEwHyp2000arc201Response;
import org.ingv.dante.model.AddEwHyp2000arcRequest;
import org.ingv.dante.model.AddEwQuake2kRequest;
import org.ingv.dante.model.AddHEwMagnitudeRequest;
import org.ingv.dante.model.AddHEwPickScnl201Response;
import org.ingv.dante.model.AddHEwPickScnlRequest;
import org.ingv.dante.model.AddHEwStrongmotionii201Response;
import org.ingv.dante.model.AddHEwStrongmotioniiRequest;
import org.ingv.dante.model.AddMagnitude201Response;
import org.ingv.dante.model.Problem;
import org.ingv.dante.model.UpdateEvent200Response;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for EarthwormApiApi
 */
@Disabled
public class EarthwormApiApiTest {

    private final EarthwormApiApi api = new EarthwormApiApi();

    /**
     * Insert a new hyp2000arc message to the DB using ew2openapi module
     *
     * This API is used to add an Earthworm hyp2000arc object.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void addEwHyp2000arcTest() throws ApiException {
        AddEwHyp2000arcRequest addEwHyp2000arcRequest = null;
        AddEwHyp2000arc201Response response = api.addEwHyp2000arc(addEwHyp2000arcRequest);
        // TODO: test validations
    }

    /**
     * Insert a new quake2k message to the DB using ew2openapi module
     *
     * This API is used to add an Earthworm quake2k object.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void addEwQuake2kTest() throws ApiException {
        AddEwQuake2kRequest addEwQuake2kRequest = null;
        UpdateEvent200Response response = api.addEwQuake2k(addEwQuake2kRequest);
        // TODO: test validations
    }

    /**
     * Insert a new magnitude message to the DB using ew2openapi module
     *
     * This API is used to add an Earthworm magnitude object.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void addHEwMagnitudeTest() throws ApiException {
        AddHEwMagnitudeRequest addHEwMagnitudeRequest = null;
        AddMagnitude201Response response = api.addHEwMagnitude(addHEwMagnitudeRequest);
        // TODO: test validations
    }

    /**
     * Insert a new pick-scnl message to the DB using ew2openapi module
     *
     * This API is used to add an Earthworm pick_scnl object.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void addHEwPickScnlTest() throws ApiException {
        AddHEwPickScnlRequest addHEwPickScnlRequest = null;
        AddHEwPickScnl201Response response = api.addHEwPickScnl(addHEwPickScnlRequest);
        // TODO: test validations
    }

    /**
     * Insert a new strongmotionii message to the DB using ew2openapi module
     *
     * This API is used to add an Earthworm strongmotionii object.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void addHEwStrongmotioniiTest() throws ApiException {
        AddHEwStrongmotioniiRequest addHEwStrongmotioniiRequest = null;
        AddHEwStrongmotionii201Response response = api.addHEwStrongmotionii(addHEwStrongmotioniiRequest);
        // TODO: test validations
    }

}
