/*
 * Dante Web Services
 *       # Introduction   Dante is an API Web Service used for iteract with earthquake data stored in database (**quakedb**); the **quakedb** database schema is used at INGV.   Use other schema would require cration of specific `Model` and `Controller` but this is the potential of web services.      Dante provides a set of routes to store message **event**, **origin**, **magnitude**, **arrival**, **...**.      # Input   As input, Dante acept:   - A `json` message (view '**store**' spec below)    - An Eartworm `json` message (view '**earthworm api**' spec below) produced by **ew2openapi** module      # Output   As output, Dante has a RESTful api foreach database table and implement three specific routes:    - `events-pref`: returns the preferred origin and the preferred magnitude from all clusterd events.    - `events`: returns the preferred origin and the preferred magnitude from the same instance.    - `event`: returns the full event (event, origins, magnitudes, arrivals, amplitude, etc...) from an **eventid** or **originid**_/_**originid**.        
 *
 * The version of the OpenAPI document: 2.45.0-dev
 * Contact: valentino.lauciani@ingv.it
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.ingv.dante.api;

import org.ingv.dante.ApiException;
import org.ingv.dante.model.AddLocalspaceRequest;
import org.ingv.dante.model.AddTypeEventRequest;
import org.ingv.dante.model.AddTypeMagnitudeRequest;
import org.ingv.dante.model.AddTypeOriginRequest;
import org.ingv.dante.model.Problem;
import org.ingv.dante.model.UpdateEventRequest;
import org.ingv.dante.model.UpdateOriginFlagRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for UpdateApi
 */
@Disabled
public class UpdateApiTest {

    private final UpdateApi api = new UpdateApi();

    /**
     * Update an existing event
     *
     * Update an existing event.&lt;/br&gt; To use this API you must be authenticated and \&quot;event.localspace_name\&quot; owner.&lt;/br&gt; More info about &#x60;event_group_id&#x60; &lt;b&gt;https://gitlab.rm.ingv.it/caravel/dante8/-/issues/69#note_60479&lt;/b&gt;
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateEventTest() throws ApiException {
        Long id = null;
        UpdateEventRequest updateEventRequest = null;
        api.updateEvent(id, updateEventRequest);
        // TODO: test validations
    }

    /**
     * Update an existing localspace
     *
     * Update an existing localspace.&lt;/br&gt; To use this API you must be authenticated.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateLocalspaceTest() throws ApiException {
        Long id = null;
        AddLocalspaceRequest addLocalspaceRequest = null;
        api.updateLocalspace(id, addLocalspaceRequest);
        // TODO: test validations
    }

    /**
     * Update an existing origin-flag
     *
     * Update an existing origin-flag.&lt;/br&gt; To use this API you must be authenticated and \&quot;origin.localspace_name\&quot; owner.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateOriginFlagTest() throws ApiException {
        Long id = null;
        UpdateOriginFlagRequest updateOriginFlagRequest = null;
        api.updateOriginFlag(id, updateOriginFlagRequest);
        // TODO: test validations
    }

    /**
     * Update an existing type_event
     *
     * Update an existing type_event.&lt;/br&gt; To use this API you must be authenticated.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateTypeEventTest() throws ApiException {
        Long id = null;
        AddTypeEventRequest addTypeEventRequest = null;
        api.updateTypeEvent(id, addTypeEventRequest);
        // TODO: test validations
    }

    /**
     * Update an existing type_magnitude
     *
     * Update an existing type_magnitude.&lt;/br&gt; To use this API you must be authenticated.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateTypeMagnitudeTest() throws ApiException {
        Long id = null;
        AddTypeMagnitudeRequest addTypeMagnitudeRequest = null;
        api.updateTypeMagnitude(id, addTypeMagnitudeRequest);
        // TODO: test validations
    }

    /**
     * Update an existing type_origin
     *
     * Update an existing type_origin.&lt;/br&gt; To use this API you must be authenticated.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateTypeOriginTest() throws ApiException {
        Long id = null;
        AddTypeOriginRequest addTypeOriginRequest = null;
        api.updateTypeOrigin(id, addTypeOriginRequest);
        // TODO: test validations
    }

}
