/*
 * Dante Web Services
 *       # Introduction   Dante is an API Web Service used for iteract with earthquake data stored in database (**quakedb**); the **quakedb** database schema is used at INGV.   Use other schema would require cration of specific `Model` and `Controller` but this is the potential of web services.      Dante provides a set of routes to store message **event**, **origin**, **magnitude**, **arrival**, **...**.      # Input   As input, Dante acept:   - A `json` message (view '**store**' spec below)    - An Eartworm `json` message (view '**earthworm api**' spec below) produced by **ew2openapi** module      # Output   As output, Dante has a RESTful api foreach database table and implement three specific routes:    - `events-pref`: returns the preferred origin and the preferred magnitude from all clusterd events.    - `events`: returns the preferred origin and the preferred magnitude from the same instance.    - `event`: returns the full event (event, origins, magnitudes, arrivals, amplitude, etc...) from an **eventid** or **originid**_/_**originid**.        
 *
 * The version of the OpenAPI document: 2.45.0-dev
 * Contact: valentino.lauciani@ingv.it
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.ingv.dante.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import org.ingv.dante.JSON;

/**
 * AddTypeMagnitude201Response
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-05-25T13:58:43.855491Z[Etc/UTC]")
public class AddTypeMagnitude201Response {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private Long id;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_PRIORITY = "priority";
  @SerializedName(SERIALIZED_NAME_PRIORITY)
  private Long priority = 0l;

  public static final String SERIALIZED_NAME_MINMAG = "minmag";
  @SerializedName(SERIALIZED_NAME_MINMAG)
  private Float minmag;

  public static final String SERIALIZED_NAME_MAXMAG = "maxmag";
  @SerializedName(SERIALIZED_NAME_MAXMAG)
  private Float maxmag;

  public static final String SERIALIZED_NAME_MINREADINGS = "minreadings";
  @SerializedName(SERIALIZED_NAME_MINREADINGS)
  private Integer minreadings;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  private String description;

  public static final String SERIALIZED_NAME_MODIFIED = "modified";
  @SerializedName(SERIALIZED_NAME_MODIFIED)
  private OffsetDateTime modified;

  public static final String SERIALIZED_NAME_INSERTED = "inserted";
  @SerializedName(SERIALIZED_NAME_INSERTED)
  private OffsetDateTime inserted;

  public AddTypeMagnitude201Response() { 
  }

  
  public AddTypeMagnitude201Response(
     OffsetDateTime modified, 
     OffsetDateTime inserted
  ) {
    this();
    this.modified = modified;
    this.inserted = inserted;
  }

  public AddTypeMagnitude201Response id(Long id) {
    
    this.id = id;
    return this;
  }

   /**
   * Unique incremental id | bigint(20)
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "14932631", value = "Unique incremental id | bigint(20)")

  public Long getId() {
    return id;
  }


  public void setId(Long id) {
    this.id = id;
  }


  public AddTypeMagnitude201Response name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Type of the magnitude | varchar(255)
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "ML-VAX", value = "Type of the magnitude | varchar(255)")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public AddTypeMagnitude201Response priority(Long priority) {
    
    this.priority = priority;
    return this;
  }

   /**
   * Type magnitude priority | int(8)
   * @return priority
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1", value = "Type magnitude priority | int(8)")

  public Long getPriority() {
    return priority;
  }


  public void setPriority(Long priority) {
    this.priority = priority;
  }


  public AddTypeMagnitude201Response minmag(Float minmag) {
    
    this.minmag = minmag;
    return this;
  }

   /**
   * Minimum magnitude value | float(4)
   * @return minmag
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1.2", value = "Minimum magnitude value | float(4)")

  public Float getMinmag() {
    return minmag;
  }


  public void setMinmag(Float minmag) {
    this.minmag = minmag;
  }


  public AddTypeMagnitude201Response maxmag(Float maxmag) {
    
    this.maxmag = maxmag;
    return this;
  }

   /**
   * Maximum magnitude value | float(4)
   * @return maxmag
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "2.2", value = "Maximum magnitude value | float(4)")

  public Float getMaxmag() {
    return maxmag;
  }


  public void setMaxmag(Float maxmag) {
    this.maxmag = maxmag;
  }


  public AddTypeMagnitude201Response minreadings(Integer minreadings) {
    
    this.minreadings = minreadings;
    return this;
  }

   /**
   * Minimum number of readings | int(8)
   * @return minreadings
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Minimum number of readings | int(8)")

  public Integer getMinreadings() {
    return minreadings;
  }


  public void setMinreadings(Integer minreadings) {
    this.minreadings = minreadings;
  }


  public AddTypeMagnitude201Response description(String description) {
    
    this.description = description;
    return this;
  }

   /**
   * Additional information | char(255)
   * @return description
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Auto added", value = "Additional information | char(255)")

  public String getDescription() {
    return description;
  }


  public void setDescription(String description) {
    this.description = description;
  }


   /**
   * Last Review | timestamp
   * @return modified
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "2016-06-22T16:52:06.260Z", value = "Last Review | timestamp")

  public OffsetDateTime getModified() {
    return modified;
  }




   /**
   * Insert time | timestamp
   * @return inserted
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "2016-06-22T16:52:06.260Z", value = "Insert time | timestamp")

  public OffsetDateTime getInserted() {
    return inserted;
  }





  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AddTypeMagnitude201Response addTypeMagnitude201Response = (AddTypeMagnitude201Response) o;
    return Objects.equals(this.id, addTypeMagnitude201Response.id) &&
        Objects.equals(this.name, addTypeMagnitude201Response.name) &&
        Objects.equals(this.priority, addTypeMagnitude201Response.priority) &&
        Objects.equals(this.minmag, addTypeMagnitude201Response.minmag) &&
        Objects.equals(this.maxmag, addTypeMagnitude201Response.maxmag) &&
        Objects.equals(this.minreadings, addTypeMagnitude201Response.minreadings) &&
        Objects.equals(this.description, addTypeMagnitude201Response.description) &&
        Objects.equals(this.modified, addTypeMagnitude201Response.modified) &&
        Objects.equals(this.inserted, addTypeMagnitude201Response.inserted);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, priority, minmag, maxmag, minreadings, description, modified, inserted);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AddTypeMagnitude201Response {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    priority: ").append(toIndentedString(priority)).append("\n");
    sb.append("    minmag: ").append(toIndentedString(minmag)).append("\n");
    sb.append("    maxmag: ").append(toIndentedString(maxmag)).append("\n");
    sb.append("    minreadings: ").append(toIndentedString(minreadings)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    modified: ").append(toIndentedString(modified)).append("\n");
    sb.append("    inserted: ").append(toIndentedString(inserted)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("id");
    openapiFields.add("name");
    openapiFields.add("priority");
    openapiFields.add("minmag");
    openapiFields.add("maxmag");
    openapiFields.add("minreadings");
    openapiFields.add("description");
    openapiFields.add("modified");
    openapiFields.add("inserted");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to AddTypeMagnitude201Response
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (AddTypeMagnitude201Response.openapiRequiredFields.isEmpty()) {
          return;
        } else { // has required fields
          throw new IllegalArgumentException(String.format("The required field(s) %s in AddTypeMagnitude201Response is not found in the empty JSON string", AddTypeMagnitude201Response.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!AddTypeMagnitude201Response.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `AddTypeMagnitude201Response` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      if (jsonObj.get("name") != null && !jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if (jsonObj.get("description") != null && !jsonObj.get("description").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `description` to be a primitive type in the JSON string but got `%s`", jsonObj.get("description").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!AddTypeMagnitude201Response.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'AddTypeMagnitude201Response' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<AddTypeMagnitude201Response> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(AddTypeMagnitude201Response.class));

       return (TypeAdapter<T>) new TypeAdapter<AddTypeMagnitude201Response>() {
           @Override
           public void write(JsonWriter out, AddTypeMagnitude201Response value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public AddTypeMagnitude201Response read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of AddTypeMagnitude201Response given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of AddTypeMagnitude201Response
  * @throws IOException if the JSON string is invalid with respect to AddTypeMagnitude201Response
  */
  public static AddTypeMagnitude201Response fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, AddTypeMagnitude201Response.class);
  }

 /**
  * Convert an instance of AddTypeMagnitude201Response to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

