/*
 * Dante Web Services
 *       # Introduction   Dante is an API Web Service used for iteract with earthquake data stored in database (**quakedb**); the **quakedb** database schema is used at INGV.   Use other schema would require cration of specific `Model` and `Controller` but this is the potential of web services.      Dante provides a set of routes to store message **event**, **origin**, **magnitude**, **arrival**, **...**.      # Input   As input, Dante acept:   - A `json` message (view '**store**' spec below)    - An Eartworm `json` message (view '**earthworm api**' spec below) produced by **ew2openapi** module      # Output   As output, Dante has a RESTful api foreach database table and implement three specific routes:    - `events-pref`: returns the preferred origin and the preferred magnitude from all clusterd events.    - `events`: returns the preferred origin and the preferred magnitude from the same instance.    - `event`: returns the full event (event, origins, magnitudes, arrivals, amplitude, etc...) from an **eventid** or **originid**_/_**originid**.        
 *
 * The version of the OpenAPI document: 2.44.0
 * Contact: valentino.lauciani@ingv.it
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.ingv.dante.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.ingv.dante.model.MagnitudeBase;
import org.ingv.dante.model.MagnitudeBaseEwMessage;
import org.ingv.dante.model.MagnitudeSchemaAllOf;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import org.ingv.dante.JSON;

/**
 * MagnitudeSchema
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-05-16T10:17:38.852243Z[Etc/UTC]")
public class MagnitudeSchema {
  public static final String SERIALIZED_NAME_EW_MESSAGE = "ewMessage";
  @SerializedName(SERIALIZED_NAME_EW_MESSAGE)
  private MagnitudeBaseEwMessage ewMessage;

  public static final String SERIALIZED_NAME_EW_LOGO = "ewLogo";
  @SerializedName(SERIALIZED_NAME_EW_LOGO)
  private Object ewLogo;

  public MagnitudeSchema() { 
  }

  public MagnitudeSchema ewMessage(MagnitudeBaseEwMessage ewMessage) {
    
    this.ewMessage = ewMessage;
    return this;
  }

   /**
   * Get ewMessage
   * @return ewMessage
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public MagnitudeBaseEwMessage getEwMessage() {
    return ewMessage;
  }


  public void setEwMessage(MagnitudeBaseEwMessage ewMessage) {
    this.ewMessage = ewMessage;
  }


  public MagnitudeSchema ewLogo(Object ewLogo) {
    
    this.ewLogo = ewLogo;
    return this;
  }

   /**
   * Get ewLogo
   * @return ewLogo
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getEwLogo() {
    return ewLogo;
  }


  public void setEwLogo(Object ewLogo) {
    this.ewLogo = ewLogo;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MagnitudeSchema magnitudeSchema = (MagnitudeSchema) o;
    return Objects.equals(this.ewMessage, magnitudeSchema.ewMessage) &&
        Objects.equals(this.ewLogo, magnitudeSchema.ewLogo);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(ewMessage, ewLogo);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MagnitudeSchema {\n");
    sb.append("    ewMessage: ").append(toIndentedString(ewMessage)).append("\n");
    sb.append("    ewLogo: ").append(toIndentedString(ewLogo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("ewMessage");
    openapiFields.add("ewLogo");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to MagnitudeSchema
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (MagnitudeSchema.openapiRequiredFields.isEmpty()) {
          return;
        } else { // has required fields
          throw new IllegalArgumentException(String.format("The required field(s) %s in MagnitudeSchema is not found in the empty JSON string", MagnitudeSchema.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!MagnitudeSchema.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `MagnitudeSchema` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      // validate the optional field `ewMessage`
      if (jsonObj.getAsJsonObject("ewMessage") != null) {
        MagnitudeBaseEwMessage.validateJsonObject(jsonObj.getAsJsonObject("ewMessage"));
      }
      // validate the optional field `ewLogo`
      if (jsonObj.getAsJsonObject("ewLogo") != null) {
        Object.validateJsonObject(jsonObj.getAsJsonObject("ewLogo"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!MagnitudeSchema.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'MagnitudeSchema' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<MagnitudeSchema> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(MagnitudeSchema.class));

       return (TypeAdapter<T>) new TypeAdapter<MagnitudeSchema>() {
           @Override
           public void write(JsonWriter out, MagnitudeSchema value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public MagnitudeSchema read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of MagnitudeSchema given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of MagnitudeSchema
  * @throws IOException if the JSON string is invalid with respect to MagnitudeSchema
  */
  public static MagnitudeSchema fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, MagnitudeSchema.class);
  }

 /**
  * Convert an instance of MagnitudeSchema to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

