/*
 * Dante Web Services
 *       # Introduction   Dante is an API Web Service used for iteract with earthquake data stored in database (**quakedb**); the **quakedb** database schema is used at INGV.   Use other schema would require cration of specific `Model` and `Controller` but this is the potential of web services.      Dante provides a set of routes to store message **event**, **origin**, **magnitude**, **arrival**, **...**.      # Input   As input, Dante acept:   - A `json` message (view '**store**' spec below)    - An Eartworm `json` message (view '**earthworm api**' spec below) produced by **ew2openapi** module      # Output   As output, Dante has a RESTful api foreach database table and implement three specific routes:    - `events-pref`: returns the preferred origin and the preferred magnitude from all clusterd events.    - `events`: returns the preferred origin and the preferred magnitude from the same instance.    - `event`: returns the full event (event, origins, magnitudes, arrivals, amplitude, etc...) from an **eventid** or **originid**_/_**originid**.        
 *
 * The version of the OpenAPI document: 2.44.0
 * Contact: valentino.lauciani@ingv.it
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.ingv.dante.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.ingv.dante.model.TypeOriginName;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import org.ingv.dante.JSON;

/**
 * ObjectTypeOrigin
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-06-13T17:32:06.904905Z[Etc/UTC]")
public class ObjectTypeOrigin {
  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private TypeOriginName name = TypeOriginName.HYPOCENTER;

  public static final String SERIALIZED_NAME_VERSION_NAME = "version_name";
  @SerializedName(SERIALIZED_NAME_VERSION_NAME)
  private String versionName;

  public static final String SERIALIZED_NAME_VERSION_VALUE = "version_value";
  @SerializedName(SERIALIZED_NAME_VERSION_VALUE)
  private Long versionValue;

  public ObjectTypeOrigin() { 
  }

  
  public ObjectTypeOrigin(
     Long versionValue
  ) {
    this();
    this.versionValue = versionValue;
  }

  public ObjectTypeOrigin name(TypeOriginName name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public TypeOriginName getName() {
    return name;
  }


  public void setName(TypeOriginName name) {
    this.name = name;
  }


  public ObjectTypeOrigin versionName(String versionName) {
    
    this.versionName = versionName;
    return this;
  }

   /**
   * Localization name (es:ew prelim,XX,WW,..) | varchar(255)
   * @return versionName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "ew prelim", value = "Localization name (es:ew prelim,XX,WW,..) | varchar(255)")

  public String getVersionName() {
    return versionName;
  }


  public void setVersionName(String versionName) {
    this.versionName = versionName;
  }


   /**
   * Define a numeric value for type origin. &lt; 100 is automatic location | bigint(20)
   * @return versionValue
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "2", value = "Define a numeric value for type origin. < 100 is automatic location | bigint(20)")

  public Long getVersionValue() {
    return versionValue;
  }





  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ObjectTypeOrigin objectTypeOrigin = (ObjectTypeOrigin) o;
    return Objects.equals(this.name, objectTypeOrigin.name) &&
        Objects.equals(this.versionName, objectTypeOrigin.versionName) &&
        Objects.equals(this.versionValue, objectTypeOrigin.versionValue);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, versionName, versionValue);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ObjectTypeOrigin {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    versionName: ").append(toIndentedString(versionName)).append("\n");
    sb.append("    versionValue: ").append(toIndentedString(versionValue)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("name");
    openapiFields.add("version_name");
    openapiFields.add("version_value");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("name");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to ObjectTypeOrigin
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (ObjectTypeOrigin.openapiRequiredFields.isEmpty()) {
          return;
        } else { // has required fields
          throw new IllegalArgumentException(String.format("The required field(s) %s in ObjectTypeOrigin is not found in the empty JSON string", ObjectTypeOrigin.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!ObjectTypeOrigin.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ObjectTypeOrigin` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : ObjectTypeOrigin.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      if (jsonObj.get("version_name") != null && !jsonObj.get("version_name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `version_name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("version_name").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ObjectTypeOrigin.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ObjectTypeOrigin' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ObjectTypeOrigin> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ObjectTypeOrigin.class));

       return (TypeAdapter<T>) new TypeAdapter<ObjectTypeOrigin>() {
           @Override
           public void write(JsonWriter out, ObjectTypeOrigin value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ObjectTypeOrigin read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ObjectTypeOrigin given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ObjectTypeOrigin
  * @throws IOException if the JSON string is invalid with respect to ObjectTypeOrigin
  */
  public static ObjectTypeOrigin fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ObjectTypeOrigin.class);
  }

 /**
  * Convert an instance of ObjectTypeOrigin to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

