/*
 * Dante Web Services
 *       # Introduction   Dante is an API Web Service used for iteract with earthquake data stored in database (**quakedb**); the **quakedb** database schema is used at INGV.   Use other schema would require cration of specific `Model` and `Controller` but this is the potential of web services.      Dante provides a set of routes to store message **event**, **origin**, **magnitude**, **arrival**, **...**.      # Input   As input, Dante acept:   - A `json` message (view '**store**' spec below)    - An Eartworm `json` message (view '**earthworm api**' spec below) produced by **ew2openapi** module      # Output   As output, Dante has a RESTful api foreach database table and implement three specific routes:    - `events-pref`: returns the preferred origin and the preferred magnitude from all clusterd events.    - `events`: returns the preferred origin and the preferred magnitude from the same instance.    - `event`: returns the full event (event, origins, magnitudes, arrivals, amplitude, etc...) from an **eventid** or **originid**_/_**originid**.        
 *
 * The version of the OpenAPI document: 2.44.0
 * Contact: valentino.lauciani@ingv.it
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.ingv.dante.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.ingv.dante.model.ObjectOriginFlagPostOutputOriginFlagInner;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import org.ingv.dante.JSON;

/**
 * ObjectOriginFlagPostOutput
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-05-25T13:59:10.427555Z[Etc/UTC]")
public class ObjectOriginFlagPostOutput {
  public static final String SERIALIZED_NAME_ORIGIN_FLAG = "origin-flag";
  @SerializedName(SERIALIZED_NAME_ORIGIN_FLAG)
  private List<ObjectOriginFlagPostOutputOriginFlagInner> originFlag = null;

  public ObjectOriginFlagPostOutput() { 
  }

  public ObjectOriginFlagPostOutput originFlag(List<ObjectOriginFlagPostOutputOriginFlagInner> originFlag) {
    
    this.originFlag = originFlag;
    return this;
  }

  public ObjectOriginFlagPostOutput addOriginFlagItem(ObjectOriginFlagPostOutputOriginFlagInner originFlagItem) {
    if (this.originFlag == null) {
      this.originFlag = new ArrayList<>();
    }
    this.originFlag.add(originFlagItem);
    return this;
  }

   /**
   * Get originFlag
   * @return originFlag
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<ObjectOriginFlagPostOutputOriginFlagInner> getOriginFlag() {
    return originFlag;
  }


  public void setOriginFlag(List<ObjectOriginFlagPostOutputOriginFlagInner> originFlag) {
    this.originFlag = originFlag;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ObjectOriginFlagPostOutput objectOriginFlagPostOutput = (ObjectOriginFlagPostOutput) o;
    return Objects.equals(this.originFlag, objectOriginFlagPostOutput.originFlag);
  }

  @Override
  public int hashCode() {
    return Objects.hash(originFlag);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ObjectOriginFlagPostOutput {\n");
    sb.append("    originFlag: ").append(toIndentedString(originFlag)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("origin-flag");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to ObjectOriginFlagPostOutput
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (ObjectOriginFlagPostOutput.openapiRequiredFields.isEmpty()) {
          return;
        } else { // has required fields
          throw new IllegalArgumentException(String.format("The required field(s) %s in ObjectOriginFlagPostOutput is not found in the empty JSON string", ObjectOriginFlagPostOutput.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!ObjectOriginFlagPostOutput.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ObjectOriginFlagPostOutput` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      JsonArray jsonArrayoriginFlag = jsonObj.getAsJsonArray("origin-flag");
      if (jsonArrayoriginFlag != null) {
        // ensure the json data is an array
        if (!jsonObj.get("origin-flag").isJsonArray()) {
          throw new IllegalArgumentException(String.format("Expected the field `origin-flag` to be an array in the JSON string but got `%s`", jsonObj.get("origin-flag").toString()));
        }

        // validate the optional field `origin-flag` (array)
        for (int i = 0; i < jsonArrayoriginFlag.size(); i++) {
          ObjectOriginFlagPostOutputOriginFlagInner.validateJsonObject(jsonArrayoriginFlag.get(i).getAsJsonObject());
        };
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ObjectOriginFlagPostOutput.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ObjectOriginFlagPostOutput' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ObjectOriginFlagPostOutput> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ObjectOriginFlagPostOutput.class));

       return (TypeAdapter<T>) new TypeAdapter<ObjectOriginFlagPostOutput>() {
           @Override
           public void write(JsonWriter out, ObjectOriginFlagPostOutput value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ObjectOriginFlagPostOutput read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ObjectOriginFlagPostOutput given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ObjectOriginFlagPostOutput
  * @throws IOException if the JSON string is invalid with respect to ObjectOriginFlagPostOutput
  */
  public static ObjectOriginFlagPostOutput fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ObjectOriginFlagPostOutput.class);
  }

 /**
  * Convert an instance of ObjectOriginFlagPostOutput to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

