/*
 * Dante Web Services
 *       # Introduction   Dante is an API Web Service used for iteract with earthquake data stored in database (**quakedb**); the **quakedb** database schema is used at INGV.   Use other schema would require cration of specific `Model` and `Controller` but this is the potential of web services.      Dante provides a set of routes to store message **event**, **origin**, **magnitude**, **arrival**, **...**.      # Input   As input, Dante acept:   - A `json` message (view '**store**' spec below)    - An Eartworm `json` message (view '**earthworm api**' spec below) produced by **ew2openapi** module      # Output   As output, Dante has a RESTful api foreach database table and implement three specific routes:    - `events-pref`: returns the preferred origin and the preferred magnitude from all clusterd events.    - `events`: returns the preferred origin and the preferred magnitude from the same instance.    - `event`: returns the full event (event, origins, magnitudes, arrivals, amplitude, etc...) from an **eventid** or **originid**_/_**originid**.        
 *
 * The version of the OpenAPI document: 2.44.0
 * Contact: valentino.lauciani@ingv.it
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.ingv.dante.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.ingv.dante.model.AddEvent201ResponseDataEventAllOf;
import org.ingv.dante.model.AddEvent201ResponseDataEventAllOfLocalspace;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import org.ingv.dante.JSON;

/**
 * ObjectStrongmotionPostOutputStrongmotionsInner
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-05-17T13:44:53.956317Z[Etc/UTC]")
public class ObjectStrongmotionPostOutputStrongmotionsInner {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private Long id;

  public static final String SERIALIZED_NAME_ID_LOCALSPACE = "id_localspace";
  @SerializedName(SERIALIZED_NAME_ID_LOCALSPACE)
  private Long idLocalspace;

  public static final String SERIALIZED_NAME_LOCALSPACE = "localspace";
  @SerializedName(SERIALIZED_NAME_LOCALSPACE)
  private AddEvent201ResponseDataEventAllOfLocalspace localspace;

  public ObjectStrongmotionPostOutputStrongmotionsInner() { 
  }

  public ObjectStrongmotionPostOutputStrongmotionsInner id(Long id) {
    
    this.id = id;
    return this;
  }

   /**
   * Unique incremental id | bigint(20)
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "14932631", value = "Unique incremental id | bigint(20)")

  public Long getId() {
    return id;
  }


  public void setId(Long id) {
    this.id = id;
  }


  public ObjectStrongmotionPostOutputStrongmotionsInner idLocalspace(Long idLocalspace) {
    
    this.idLocalspace = idLocalspace;
    return this;
  }

   /**
   * Localspace Id | bigint(19)
   * @return idLocalspace
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "182491", value = "Localspace Id | bigint(19)")

  public Long getIdLocalspace() {
    return idLocalspace;
  }


  public void setIdLocalspace(Long idLocalspace) {
    this.idLocalspace = idLocalspace;
  }


  public ObjectStrongmotionPostOutputStrongmotionsInner localspace(AddEvent201ResponseDataEventAllOfLocalspace localspace) {
    
    this.localspace = localspace;
    return this;
  }

   /**
   * Get localspace
   * @return localspace
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public AddEvent201ResponseDataEventAllOfLocalspace getLocalspace() {
    return localspace;
  }


  public void setLocalspace(AddEvent201ResponseDataEventAllOfLocalspace localspace) {
    this.localspace = localspace;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ObjectStrongmotionPostOutputStrongmotionsInner objectStrongmotionPostOutputStrongmotionsInner = (ObjectStrongmotionPostOutputStrongmotionsInner) o;
    return Objects.equals(this.id, objectStrongmotionPostOutputStrongmotionsInner.id) &&
        Objects.equals(this.idLocalspace, objectStrongmotionPostOutputStrongmotionsInner.idLocalspace) &&
        Objects.equals(this.localspace, objectStrongmotionPostOutputStrongmotionsInner.localspace);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, idLocalspace, localspace);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ObjectStrongmotionPostOutputStrongmotionsInner {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    idLocalspace: ").append(toIndentedString(idLocalspace)).append("\n");
    sb.append("    localspace: ").append(toIndentedString(localspace)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("id");
    openapiFields.add("id_localspace");
    openapiFields.add("localspace");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to ObjectStrongmotionPostOutputStrongmotionsInner
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (ObjectStrongmotionPostOutputStrongmotionsInner.openapiRequiredFields.isEmpty()) {
          return;
        } else { // has required fields
          throw new IllegalArgumentException(String.format("The required field(s) %s in ObjectStrongmotionPostOutputStrongmotionsInner is not found in the empty JSON string", ObjectStrongmotionPostOutputStrongmotionsInner.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!ObjectStrongmotionPostOutputStrongmotionsInner.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ObjectStrongmotionPostOutputStrongmotionsInner` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      // validate the optional field `localspace`
      if (jsonObj.getAsJsonObject("localspace") != null) {
        AddEvent201ResponseDataEventAllOfLocalspace.validateJsonObject(jsonObj.getAsJsonObject("localspace"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ObjectStrongmotionPostOutputStrongmotionsInner.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ObjectStrongmotionPostOutputStrongmotionsInner' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ObjectStrongmotionPostOutputStrongmotionsInner> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ObjectStrongmotionPostOutputStrongmotionsInner.class));

       return (TypeAdapter<T>) new TypeAdapter<ObjectStrongmotionPostOutputStrongmotionsInner>() {
           @Override
           public void write(JsonWriter out, ObjectStrongmotionPostOutputStrongmotionsInner value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ObjectStrongmotionPostOutputStrongmotionsInner read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ObjectStrongmotionPostOutputStrongmotionsInner given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ObjectStrongmotionPostOutputStrongmotionsInner
  * @throws IOException if the JSON string is invalid with respect to ObjectStrongmotionPostOutputStrongmotionsInner
  */
  public static ObjectStrongmotionPostOutputStrongmotionsInner fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ObjectStrongmotionPostOutputStrongmotionsInner.class);
  }

 /**
  * Convert an instance of ObjectStrongmotionPostOutputStrongmotionsInner to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

