/*
 * Dante Web Services
 *       # Introduction   Dante is an API Web Service used for iteract with earthquake data stored in database (**quakedb**); the **quakedb** database schema is used at INGV.   Use other schema would require cration of specific `Model` and `Controller` but this is the potential of web services.      Dante provides a set of routes to store message **event**, **origin**, **magnitude**, **arrival**, **...**.      # Input   As input, Dante acept:   - A `json` message (view '**store**' spec below)    - An Eartworm `json` message (view '**earthworm api**' spec below) produced by **ew2openapi** module      # Output   As output, Dante has a RESTful api foreach database table and implement three specific routes:    - `events-pref`: returns the preferred origin and the preferred magnitude from all clusterd events.    - `events`: returns the preferred origin and the preferred magnitude from the same instance.    - `event`: returns the full event (event, origins, magnitudes, arrivals, amplitude, etc...) from an **eventid** or **originid**_/_**originid**.        
 *
 * The version of the OpenAPI document: 2.45.0-dev
 * Contact: valentino.lauciani@ingv.it
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.ingv.dante.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import org.ingv.dante.JSON;

/**
 * StrongmotioniiBaseEwMessageRSAInner
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-05-16T10:17:17.225510Z[Etc/UTC]")
public class StrongmotioniiBaseEwMessageRSAInner {
  public static final String SERIALIZED_NAME_VALUE = "value";
  @SerializedName(SERIALIZED_NAME_VALUE)
  private Double value;

  public static final String SERIALIZED_NAME_PERIOD = "period";
  @SerializedName(SERIALIZED_NAME_PERIOD)
  private Double period;

  public StrongmotioniiBaseEwMessageRSAInner() { 
  }

  public StrongmotioniiBaseEwMessageRSAInner value(Double value) {
    
    this.value = value;
    return this;
  }

   /**
   * RSA(response spectrum accel) value for period
   * @return value
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "0.000724", value = "RSA(response spectrum accel) value for period")

  public Double getValue() {
    return value;
  }


  public void setValue(Double value) {
    this.value = value;
  }


  public StrongmotioniiBaseEwMessageRSAInner period(Double period) {
    
    this.period = period;
    return this;
  }

   /**
   * Period
   * @return period
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "0.3", value = "Period")

  public Double getPeriod() {
    return period;
  }


  public void setPeriod(Double period) {
    this.period = period;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StrongmotioniiBaseEwMessageRSAInner strongmotioniiBaseEwMessageRSAInner = (StrongmotioniiBaseEwMessageRSAInner) o;
    return Objects.equals(this.value, strongmotioniiBaseEwMessageRSAInner.value) &&
        Objects.equals(this.period, strongmotioniiBaseEwMessageRSAInner.period);
  }

  @Override
  public int hashCode() {
    return Objects.hash(value, period);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StrongmotioniiBaseEwMessageRSAInner {\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    period: ").append(toIndentedString(period)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("value");
    openapiFields.add("period");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to StrongmotioniiBaseEwMessageRSAInner
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (StrongmotioniiBaseEwMessageRSAInner.openapiRequiredFields.isEmpty()) {
          return;
        } else { // has required fields
          throw new IllegalArgumentException(String.format("The required field(s) %s in StrongmotioniiBaseEwMessageRSAInner is not found in the empty JSON string", StrongmotioniiBaseEwMessageRSAInner.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!StrongmotioniiBaseEwMessageRSAInner.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `StrongmotioniiBaseEwMessageRSAInner` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!StrongmotioniiBaseEwMessageRSAInner.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'StrongmotioniiBaseEwMessageRSAInner' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<StrongmotioniiBaseEwMessageRSAInner> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(StrongmotioniiBaseEwMessageRSAInner.class));

       return (TypeAdapter<T>) new TypeAdapter<StrongmotioniiBaseEwMessageRSAInner>() {
           @Override
           public void write(JsonWriter out, StrongmotioniiBaseEwMessageRSAInner value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public StrongmotioniiBaseEwMessageRSAInner read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of StrongmotioniiBaseEwMessageRSAInner given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of StrongmotioniiBaseEwMessageRSAInner
  * @throws IOException if the JSON string is invalid with respect to StrongmotioniiBaseEwMessageRSAInner
  */
  public static StrongmotioniiBaseEwMessageRSAInner fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, StrongmotioniiBaseEwMessageRSAInner.class);
  }

 /**
  * Convert an instance of StrongmotioniiBaseEwMessageRSAInner to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

